apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: flask
      port: 5001
      targetPort: 5000
  type: LoadBalancer